apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gitops
  namespace: default
  labels:
    app: nginx-gitops
    version: v7.0.0
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-gitops
  template:
    metadata:
      labels:
        app: nginx-gitops
        version: v7.0.0
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: ENVIRONMENT
          value: "production"
        volumeMounts:
        - name: nginx-config
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
