apiVersion: v1
kind: Service
metadata:
  name: nginx-gitops-service
  namespace: default
  labels:
    app: nginx-gitops
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: nginx-gitops
