apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manmohan-nginx-production
  namespace: argocd
  labels:
    app: nginx-gitops
    environment: production
    owner: manmohan
spec:
  project: default
  source:
    repoURL: https://github.com/mmparmar553/eks-gitops-manmohan.git
    targetRevision: HEAD
    path: environments/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: 'Owner'
    value: 'Manmohan'
  - name: 'Environment'
    value: 'Production'
  - name: 'Description'
    value: 'Production Nginx deployed via GitOps by Manmohan'
