apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../nginx-app

patchesStrategicMerge:
- replica-patch.yaml

namePrefix: prod-
namespace: production

commonLabels:
  environment: production
  owner: manmohan
